version: "2"
services:
  api:
    container_name: api
    restart: always
    build: ./
    links: 
      - db
    ports: 
      - "3000:3000"
    volumes: 
      - ./:/app
      - /app/node_modules
    depends_on: 
      - db
  db:
    container_name: db
    image: mongo
    ports: 
      - "27017:27017"
    restart: always
    # volumes: 
    #   - ./data:/data/db